baseURL = 'https://example.org/'
languageCode = 'ja'
title = 'ãƒ‡ãƒ¼ã‚¿ãƒ“ã‚¸ãƒ¥ã‚¢ãƒ©ã‚¤ã‚¼ãƒ¼ã‚·ãƒ§ãƒ³è¬›ç¿’'
theme = 'stack'
defaultContentLanguage = 'ja'

[pagination]
pagerSize = 10

[params]
description = 'æœ¬è¬›ç¿’ã¯ã€ãƒãƒ¼ã‚±ãƒ†ã‚£ãƒ³ã‚°ã€ã‚»ãƒ¼ãƒ«ã‚¹ãªã©ã®ãƒ“ã‚¸ãƒã‚¹ãƒ‘ãƒ¼ã‚½ãƒ³ã‚„ã€ãƒ‡ã‚¶ã‚¤ãƒŠãƒ¼ã€ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ãªã©ã®ã‚¯ãƒªã‚¨ã‚¤ã‚¿ãƒ¼ã€ä¼æ¥­çµŒå–¶è€…ã€ã‚³ãƒ³ã‚µãƒ«ã‚¿ãƒ³ãƒˆã€è¡Œæ”¿é–¢ä¿‚è€…ã€è­°ä¼šè­°å“¡ãªã©ã€ãƒ‡ãƒ¼ã‚¿æ´»ç”¨ã«é–¢ã‚ã‚‹å…¨ã¦ã®è·æ¥­ã®æ–¹ã‚’å¯¾è±¡ã«ã—ã¦ã„ã¾ã™ã€‚'
mainSections = ['posts']
featuredImageField = 'image'
lightMode = 'auto'

[params.sidebar]
emoji = 'ğŸ“Š'
subtitle = 'æœ¬è¬›ç¿’ã¯ãƒ‡ãƒ¼ã‚¿æ´»ç”¨ã«é–¢ã‚ã‚‹å…¨ã¦ã®è·æ¥­ã®æ–¹ã‚’å¯¾è±¡ã«ã—ã¦ã„ã¾ã™ã€‚'
compact = false

[menus]
  [[menus.main]]
  name = 'ãƒ›ãƒ¼ãƒ '
  pageRef = '/'
  weight = 1
